name: CMake test on Windows 2022 platform

on:
  push:
    branches: 
      - master
      - devel
  pull_request:
    branches:
      - master
      - devel

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v3

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -S . -DCMAKE_INSTALL_PREFIX=${{github.workspace}}/install

    - name: Build
      run: cmake --build ${{github.workspace}}/build --target install --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest --build-config ${{env.BUILD_TYPE}} --build-target install
